files:
  - source: /lang/en/action-en.json
    translation: /lang/%locale%/action-%locale%.json
  - source: /lang/en/en.json
    translation: /lang/%locale%/%locale%.json
  - source: /lang/en/kingmaker-en.json
    translation: /lang/%locale%/kingmaker-%locale%.json
  - source: /lang/en/re-en.json
    translation: /lang/%locale%/re-%locale%.json
